version: '3'

services:
  bot:
    container_name: starryknight_bot
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '3000:3000'

  db:
    image: postgres:alpine
    container_name: starryknight_database
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
